module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/KUhcRsvJIYE6outjzlj4FA?mode=wwt',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/7sx6cd.jpg',
    NEWSLETTER_JID: '120363419188836934@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐘𝐎𝐀𝐍𝐍-𝐌𝐃',
    OWNER_NAME: '𝐘𝐎𝐀𝐍𝐍-𝐎𝐅𝐅𝐂𝐈𝐀𝐋',
    OWNER_NUMBER: '2250575532061',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴍᴀᴅᴇ ʙʏ ʏᴏᴀɴɴ-ᴏғғɪᴄɪᴀʟ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbB01rxElagqKvvvbR0a'
};
